### PR TITLE
Update customization.md

### PR DESCRIPTION
**Pull request by BesrourMS**
New Theme For Pico CMS

### CODE REVIEW

**Comment by PhrozenByte** [comment]
:+1:

**Comment by smcdougall** [comment]
May I suggest the change:

`A "Coming Soon" Theme For Pico CMS`

Otherwise it sounds almost like this "Launch" theme is the one that's "coming soon". :wink:

**Comment by smcdougall** [comment]
And great, another theme I've got to screenshot for our Super Secret* Customization Redesign. (https://github.com/picocms/Pico/pull/358)

*not really a secret at all

**Comment by PhrozenByte** [comment]
Done, see c1e3e9c. Hopefully we can merge #358 soon, I'm so used to @smcdougall's great work that our current page looks sooooo ugly... :laughing:

**Comment by smcdougall** [comment]
It really does.  I often forget that my working copy isn't what the real site looks like yet. :laughing:

**Pull request merged**
