### PR TITLE
Nitrous.io Quickstart button

### PR DESCRIPTION
**Pull request by yeouchien**
Added Nitrous Quickstart files so anyone can quickly spin up a free, cloud dev environment to start using this repo. Clicking the Quickstart button will automatically clone this repo and will install and configure any required packages.

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Thank you for your PR @yeouchien! Can you please give us a brief overview about what nitrous.io is and what it can do for users and plugin+theme developers of Pico? What's the advantage for Pico's core developers and the Pico project in whole? Why should we promote such a service in general and why should we promote this particular project?

@picocms @theshka

**Comment by yeouchien** [comment]
Hey @PhrozenByte ! 
We just want to make it incredibly quick and easy to contribute themes & plugins for Pico. The QuickStart button provides a way to create a sandbox Pico dev. environment with everything setup and installed to start building things right away.

We’ve found that reducing the friction in getting started helps considerably with engaging more developers to participate in open source projects. There’s also some really powerful “google-docs” style collaboration features so developers can pair program and help each other out. It’s 100% free for up to 2 projects.

All the best.

**Comment by smcdougall** [comment]
I don't know, I don't have a good feeling about this.  It's one thing to support Pico on your platform. In itself, that seems like an okay idea.  It's another thing entirely to include a section about it in Pico's readme (or even on the website for that matter).  At that point it would appear not just to be supported, but *endorsed* by Pico.  Neither of which are really the case.

Furthermore, let's be honest here, this is advertising.  Plain and simple.  I don't think that Pico should be advertising for a service that it's not affiliated with, even if it did provide a good service.

I don't think there's any benefit to this either.  I feel like current users will be unlikely to need such a service, and may not appreciate being advertised to.  More importantly though, I feel like this could be confusing to new users.  With such a prominent location in the readme, new users may feel that this is the *recommended* option for setting up Pico, rather than just a third party service.

My vote is No.  If you want to include a Pico Quick Start option on nitrous.io, great, more power to your users, but I don't think the advertisement for it belongs *in* Pico itself.

**Comment by PhrozenByte** [comment]
Thank you @smcdougall for elaborating this, I'm inclined to agree with you.
Unfortunately @yeouchien we can't accept your PR, thanks for your contribution anyway!

**Pull request closed without merging**
