### PR TITLE
Pico 1.0 development & release process

### PR DESCRIPTION
**Pull request by theshka**
Expanded the Build & Release section as per #268 so far. Still not sure where to announce the releases or if we even should. Is there anything missing? Incorrect?

### CODE REVIEW

**Comment by theshka** [comment]
I was looking through some other repositories that auto-generate their documentation and upload to the gh-pages branch, and although I know for fact that this commit doesn't work, I feel like I'm on the cusp of something here... Could you take a look at https://github.com/theshka/Pico/commit/f062640bb1e87c82108067d238b47e7289ea11df @PhrozenByte?

**Comment by PhrozenByte** [comment]
Sorry, I thought it would be faster when I make the necessary changes by myself instead of listing all steps. Great idea anyway :+1: It works just fine now :smiley:

**Comment by theshka** [comment]
No need to apologize at all @PhrozenByte , thanks for cleaning up the idea. I'm just happy we can have all this documentation generation happen automatically for the next release :grin:

**Comment by PhrozenByte** [comment]
What a ordeal... Complexity exploded... But works great. See [regular commit build](https://travis-ci.org/PhrozenByte/Pico/jobs/93274162) and [release build](https://travis-ci.org/PhrozenByte/Pico/jobs/93269616).

**Comment by theshka** [comment]
:boom::exclamation: I think that it looks great @PhrozenByte ! 

You've made the script highly reusable, for every type of commit, branch and tags!, accounted for the potential race conditions, and tested that it works ... if you're confident with it -- merge at will. :smile:

**Comment by PhrozenByte** [comment]
Thanks :smiley:
I actually didn't take a closer look to the doc changes yet, I'll catch up on this in the next days.

**Comment by PhrozenByte** [comment]
I don't think it's necessary to describe the build & release process in such detail, especially not what Travis automates for us - one can look into the `.travis.yml` to find out the exact steps. A short paragraph like

> We're using [Travis CI](https://travis-ci.org/) to automate the build & release process. It generates and deploys [phpDoc](http://phpdoc.org/) class docs for new releases and on every commit to the `master` branch. Travis also prepares new releases by creating Pico's pre-built packages and uploading them to GitHub. You can trigger this process by pushing a new Git Tag, what references a (usually empty) Commit which message follows the following template: `...`

should be sufficient. The "Analysis phase" actually isn't relevant for the build & release process (why should one draft a new release on a previously failing build? :smile:). The manual steps should be in continuous text, the whole section seems so overwhelming otherwise. Btw, we always have to amend the release on GitHub, see https://github.com/picocms/Pico/issues/268#issuecomment-154492172.

**Comment by PhrozenByte** [comment]
I've added [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer), it [basically tests code submissions](https://github.com/picocms/Pico/blob/enhancement/build-release/phpcs.xml) against PSR-2 coding standards. Any comments about it?

Thank you for your amendments, it's now very close to perfection! :+1: :smiley:

I've converted the Issues template to continuous text and slightly updated the build & release process section. I hope the changes are okay, can you please approve them? If this is the case, you can merge the PR afterwards. :smiley:

**Comment by theshka** [comment]
I'm absolutely fine with the Code Sniffer checking for PSR compliance. :+1:  Out of curiosity, does the Travis build fail if it detects a violation, or does it correct it and move on?

**Comment by PhrozenByte** [comment]
The Travis build fails (i.e. shows a warning, but doesn't correct anything), but still executes all subsequent commands of the `script` section. See https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step:

> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result.
>
> In the example above, if `bundle exec rake` build returns an exit code of 1, the following command `bundle exec rake builddoc` is still run, but the build will result in a failure.

Because we don't have any subsequent commands in the `script` section, it actually stops after a failure, i.e. Travis neither updates the docs nor deploys new releases. This actually is intended, some checks of PHP_CodeSniffer are fatal (e.g. PHP parse errors), very serious (e.g. the deprecated or performance warnings) and I personally even consider PSR-2-violations as a contradiction to our "deployable" requirement when pushing to `master`.

**Pull request merged**
