### PR TITLE
Website: Update custom Pico styling

### PR DESCRIPTION
**Pull request by PhrozenByte**
The [Webpaint theme](http://themes.iki-bir.com/webpaint/multipage/full/) is a dark theme - transforming it into an light theme (8deb744fed2120892678e8e333787e2ae7670200) makes it, to say it in @smcdougall's words, "loose a few points of elegance"... I turned it back into a dark theme, but added a gradient to the header to present Pico's "corporate color" a little more prominent.

**Live demo:** http://phrozenbyte.github.io/Pico/
(Note: clicking on links doesn't work, you must change URLs manually)

pico_-_a_stupidly_simple _blazing_fast _flat_file_cms _-_2015-12-16_23 12 17

### CODE REVIEW

**Comment by PhrozenByte** [comment]
By the way: The gradient is cut off on purpose, letting the gradient span over the banner - even with a radial gradient - makes it look a little odd, isn't it?

pico_-_a_stupidly_simple _blazing_fast _flat_file_cms _-_2015-12-16_23 08 42

```css
.top-wrapper {
    background: radial-gradient(farthest-side at top left, #2eae9b 120px, #2a2a2a 40%);
}
.top-wrapper header { background: transparent; }
.top-wrapper .banner .slotholder { opacity: 0 !important; }
```

**Comment by smcdougall** [comment]
:+1: Nice. That cutoff gradient does seem a little odd though, but I think I've got a solution.

Try adding this :wink::
.top-wrapper header {
    border-bottom: 1px solid transparent;
    border-image: linear-gradient(135deg, white, #2A2A2A 40%) 1;
}

FYI, I've never actually used `border-image` before.  I just thought it really needed a gradient bottom border so I looked up how to do it.  Might have to remember this for the future though...

pico

**Comment by PhrozenByte** [comment]
Greate idea, I've added the border :+1: :smiley:

**Comment by theshka** [comment]
Theme looks great @PhrozenByte, thanks for keeping in mind that we are trying to unify the branding of Pico in your rewrite.

**Pull request merged**
