### PR TITLE
New Pico CMS theme

### PR DESCRIPTION
**Pull request by BesrourMS**

### CODE REVIEW

**Comment by PhrozenByte** [comment]
As always: Looks great! :+1:

**Comment by Chris2011** [comment]
What is the name of it?

**Comment by Chris2011** [comment]
Ok I got it, Identity right?

**Comment by smcdougall** [comment]
Nope, "Personal", thought Identity is another good one of a similar vein that he's ported.

**Comment by Chris2011** [comment]
Ok thx.

**Comment by smcdougall** [comment]
Np.  Just happened to be looking at this thread when you asked. :wink:

**Pull request merged**
