### PR TITLE
Changed content to match docs changes.

### PR DESCRIPTION
**Pull request by smcdougall**
Merged the changes from #303 into this file.  Tried to preserve all the differences (such as escaping characters and the links in the table), but let me know if I've missed any.

Also, is there a reason this file has manual line breaks?  It displays in Pico about the same either way, so the only real difference would be if someone was viewing it in a text editor without word wrap.

I'd prefer to remove them to keep this content closer to what's in the Docs.  Right now it's inconsistent, with the new section not having any manual line breaks.  Also, removing the manual line breaks would make it look a little cleaner on Git / GitHub, which currently tells me I've made 30(!) Deletions instead of 10-13 or so.

Finally, it would be nice to either have a way to generate this file automatically or to mark the sections that must be changed between the Docs version and the Index version (extra tags added, escaped characters, links, etc).

As usual, let me know any changes you'd like to see to this file or #303 before merging them and I'll get it done. :smiley:

### CODE REVIEW

**Comment by smcdougall** [comment]
Actually, one idea could be to use twig comments to hide the changes inside the docs version that way if you copied over `index.md`'s content, you wouldn't be clobbering the changes you needed to preserve. You'd just have to remember to swap out or uncomment the changes.

`{# some changed text or tags #}`

**Comment by PhrozenByte** [comment]
As our `CONTRIBUTING.md` states, the inline user docs *must* follow a hard line length of 80 characters. This improves readability in text editors. This inconsistency to the user docs on our website is due to technical reasons. A automatic syncing technique isn't desirable, the inline user docs should be an abstract of a much more extensive user doc on our website, what is just currently missing. Thanks for your PR anyway :+1:

**Comment by smcdougall** [comment]
Okay, I'll get that updated shortly. It doesn't matter as much to me, it's just easier to edit without the line breaks. :wink:  Either way, I'd rather see it consistent. I just wanted to ask before I formatted it one way or the other.

What about the content? I tried to make a few sections more readable, but only in that first section I was working on.

At some point, I'd like to look over *all* the docs and clean them up accordingly. :smile:

**Comment by PhrozenByte** [comment]
Thank you @smcdougall :+1:

**Pull request merged**
