### PR TITLE
Catch YAML parse errors (2)

### PR DESCRIPTION
**Pull request by PhrozenByte**
Possible solution for #292 (alternative solution: #293), catches all `\Symfony\Component\Yaml\Exception\ParseException` except for the current page and adds a `YAML_ParseError` meta variable with the error message. Therefore browsing to the erroneous page still shows the exception.

### CODE REVIEW

**Comment by smcdougall** [comment]
Finally had a chance to test this and then realized... if the YAML error is stored as only a *meta* variable, it can't actually be used for anything because it would only be accessible on the page that's giving the exception.  I tried accessing it though the `page` variable, but I couldn't make that work either.

**Comment by PhrozenByte** [comment]
Since Pico 1.0 the meta data of all pages is available through `$pages`, therefore you can read the error string via `$pages[...]['meta']['YAML_ParseError']`.

However, you can't do anything meaningful with it :wink: The only use case I can think of is highlighting the malicious page in a admin plugin...

**Comment by smcdougall** [comment]
Yeah, I thought it should be available within `pages`, but I couldn't get it to work.  I was probably just doing something wrong.  Didn't really have the chance to properly focus on it, but I'll play around with it more soon.

I'm hoping to use it in a fashion similar to your example in #293, to help prevent `toc` errors (or other YAML errors) in [NotePaper](https://github.com/smcdougall/NotePaper).

**Comment by smcdougall** [comment]
@PhrozenByte Yeah... I must have been really tired from the holidays because it's pretty clear in those comments that I wasn't even *thinking* clearly let alone coding properly.

Anyway, here's what I had in mind back then, finally coded.  It'll be in the next version of [NotePaper](https://github.com/smcdougall/NotePaper), which I should be done with soon.  I've been so busy cramming new features into NotePaper that I could have released several versions by now. :unamused: 

yaml error example

These warnings will appear on every page (except obviously the one that throws the exception when browsed to).  The idea is that it would be helpful to a user who has either edited a few files and doesn't know which one is causing trouble or who hasn't yet realized there's an error.

Thought I'd share, since to my knowledge no one else has implemented a use for your `YAML_ParseError` variable yet. :wink:

**Comment by PhrozenByte** [comment]
Looks great! :+1: :smiley:

**Comment by smcdougall** [comment]
Thanks! :smile:

**Pull request merged**
